services:
  - type: web
    name: rapports-kourel
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd rapports-kourel && rm -rf node_modules && npm install && npm run build
    startCommand: cd rapports-kourel && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
